# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6466b9f0caa40467754d188788e4b4933028ce520b86b0373636c4d9bf5aa1b9aab1736a36a231b3723dd2a36bd16d50998e5e74eebb975c96eb6056b49c7035

test:
  secret_key_base: 8f55f76e2e7fa2369076c765179ed6bca37cf5592b15352ec1e1369fa1319806b6d0e7a69d723605420fb6a4350db5de9cda634cd5f4817f879a1b0f92054bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
